---

- hosts: all
  vars:
    packages:
      - name: apache2
        require: true
      - name: libapache2-mod-php
        require: true
      - name: libapache2-mod-php
        require: true
      - name: httpd
        require: true
        package: dnf
  become: true
  tasks:

  - name: install {{ item.name }} for Ubuntu servers
    apt:
      name: "{{ item.name }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu" && require == true

  - name: install {{ item.name }} for CentOS servers
    dnf:
      name: "{{ item.name}}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS" && item.require == true && item.package == dnf
  
  loop: "{{ packages }}"